package br.udesc.doo2.cantina.view.cliente;

import br.udesc.doo2.cantina.controller.ComentarioController;
import br.udesc.doo2.cantina.controller.ManutencaoCadastroController;
import br.udesc.doo2.cantina.controller.PedidoController;
import br.udesc.doo2.cantina.dao.ComentarioDAO;
import br.udesc.doo2.cantina.dao.PedidoDAO;
import br.udesc.doo2.cantina.dao.RefeicaoDAO;
import br.udesc.doo2.cantina.model.Cliente;
import br.udesc.doo2.cantina.model.Refeicao;
import br.udesc.doo2.cantina.repository.ComentarioRepository;
import br.udesc.doo2.cantina.view.AlterarCadastroView;
import br.udesc.doo2.cantina.view.administrador.ConsultarPedidosView;
import java.time.LocalDate;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;

public class HomeClienteView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeClienteView.class.getName());

    // Cliente autenticado que abriu esta tela - usado pelas próximas
    // funcionalidades (Pedido, Comentário, Alterar Cadastro) para saber
    // "quem" está operando, sem precisar logar de novo.
    private final Cliente clienteLogado;
    private Refeicao refeicaoDoDia;

    public HomeClienteView(Cliente clienteLogado) {
        this.clienteLogado = clienteLogado;
        initComponents();
        txtRefeiçãodoDiaHomeCliente.setEditable(false);
        btnFazerPedidoHomeCliente.addActionListener(e -> abrirTelaPedido());
        btnEnviarComentario.addActionListener(e -> abrirTelaComentario());
        btnAlterarCadastroHomeCliente.addActionListener(e -> abrirTelaAlterarCadastro());
        carregarRefeicaoDoDia();
    }
    
    private void carregarRefeicaoDoDia() {
        try {
            refeicaoDoDia = new RefeicaoDAO().buscarPorData(LocalDate.now());
            txtRefeiçãodoDiaHomeCliente.setText(
                    refeicaoDoDia.getDescricao()
                    + " | R$ " + String.format("%.2f", refeicaoDoDia.getPreco())
            );
            btnFazerPedidoHomeCliente.setEnabled(true);
        } catch (NoResultException e) {
            txtRefeiçãodoDiaHomeCliente.setText(
                    "Nenhuma refeicao cadastrada para hoje."
            );
            btnFazerPedidoHomeCliente.setEnabled(false);
        } catch (RuntimeException e) {
            txtRefeiçãodoDiaHomeCliente.setText(
                    "Nao foi possivel carregar a refeicao do dia."
            );
            btnFazerPedidoHomeCliente.setEnabled(false);
        }
    }

    private void abrirTelaPedido() {
        if (refeicaoDoDia == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Nenhuma refeicao cadastrada para hoje."
            );
            return;
        }

        new PedidoController(
                new PedidoView(),
                new PedidoDAO(),
                clienteLogado,
                refeicaoDoDia
        );
    }
    public Cliente getClienteLogado() {
        return clienteLogado;
    }
    
    public void abrirTelaComentario() {
        ComentarioView view = new ComentarioView();
        ComentarioRepository repository = new ComentarioDAO();
        new ComentarioController(view, repository, getClienteLogado());
    }
    
    private void abrirTelaAlterarCadastro() {
        AlterarCadastroView view = new AlterarCadastroView(clienteLogado);
        new ManutencaoCadastroController(view);
        view.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRefeiçãodoDiaHomeCliente = new javax.swing.JTextField();
        btnFazerPedidoHomeCliente = new javax.swing.JButton();
        btnEnviarComentario = new javax.swing.JButton();
        btnAlterarCadastroHomeCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Refeição do dia:");

        btnFazerPedidoHomeCliente.setText("Fazer Pedido");

        btnEnviarComentario.setText("Enviar Comentario");

        btnAlterarCadastroHomeCliente.setText("Alterar Cadastro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEnviarComentario, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(btnFazerPedidoHomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(txtRefeiçãodoDiaHomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(btnAlterarCadastroHomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRefeiçãodoDiaHomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFazerPedidoHomeCliente)
                .addGap(18, 18, 18)
                .addComponent(btnEnviarComentario)
                .addGap(18, 18, 18)
                .addComponent(btnAlterarCadastroHomeCliente)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // O main() de preview isolado não tem um Cliente real disponível.
        // Botei null só para visualização da tela no NetBeans.
        // Depois a tela é sempre aberta pelo LoginController com o Cliente autenticado.
        java.awt.EventQueue.invokeLater(() -> new HomeClienteView(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCadastroHomeCliente;
    private javax.swing.JButton btnEnviarComentario;
    private javax.swing.JButton btnFazerPedidoHomeCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtRefeiçãodoDiaHomeCliente;
    // End of variables declaration//GEN-END:variables
}
