/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.udesc.doo2.cantina.view.administrador;

import br.udesc.doo2.cantina.exception.OpcaoCarneException;
import br.udesc.doo2.cantina.model.OpcaoCarne;
import java.awt.event.ActionListener;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUSTAVO
 */
public class CadastrarCarnesView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastrarCarnesView.class.getName());

    /**
     * Creates new form CadastrarCarnesView
     */
    public CadastrarCarnesView() {
        initComponents();
        
        DefaultTableCellRenderer cabecalho = (DefaultTableCellRenderer) tblCarnes.getTableHeader().getDefaultRenderer();

        cabecalho.setHorizontalAlignment(SwingConstants.CENTER);
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblCarnes.getColumnCount(); i++) {
            tblCarnes.getColumnModel()
                   .getColumn(i)
                   .setCellRenderer(centralizado);
        }
    }
    
    public void adicionarAcaoBtnCadastrar(ActionListener acao) {
        btnCadastrarCarne.addActionListener(acao);
    }
    
    public void apresentarTela() {
        setVisible(true);
    }
    
    public void initTblCarnes(Set<OpcaoCarne> carnes) {
        DefaultTableModel modelo = (DefaultTableModel) tblCarnes.getModel();
        modelo.setRowCount(0);
        for (OpcaoCarne o : carnes) {
            modelo.addRow(new Object[]{
            o.getId(),
            o.getNome(),
            o.getQuantidadeDisponivel()
            });
        }
    }
    
    public String getNome() throws OpcaoCarneException {
        if(txtNomeCarne.getText().trim().isEmpty())
            throw new OpcaoCarneException("Preencha o nome da carne");
        return txtNomeCarne.getText();
    }
    
    public int getQuantidade() throws OpcaoCarneException {
        String QuantidadeString = txtQuantidade.getText();
        
        try {
            int quantidade = Integer.parseInt(QuantidadeString);
            
            if (quantidade <= 0) {
                throw new OpcaoCarneException("A quantidade não pode ser menor que 1");
            } return quantidade;
        } catch (NumberFormatException ex){
            throw new OpcaoCarneException("Informe uma quantidade válida");
        }
    }

    public void apresentarMensagem(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
    
    public void limparTela(){
        txtNomeCarne.setText("");
        txtQuantidade.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeCarne = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCadastrarCarne = new javax.swing.JButton();
        txtQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarnes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Opções de Carnes");

        jLabel2.setText("Nome da Carne:");

        btnCadastrarCarne.setText("Cadastrar");

        jLabel3.setText("Quantidade Disponível:");

        tblCarnes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarnes);
        if (tblCarnes.getColumnModel().getColumnCount() > 0) {
            tblCarnes.getColumnModel().getColumn(0).setResizable(false);
            tblCarnes.getColumnModel().getColumn(1).setResizable(false);
            tblCarnes.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadastrarCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarCarne)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCarne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarnes;
    private javax.swing.JTextField txtNomeCarne;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
